/**
 * download-fonts.mjs
 * Downloads Cormorant Garamond + Jost woff2 files from Google Fonts
 * and writes a self-hosted @font-face CSS snippet.
 * Run: node scripts/download-fonts.mjs
 */

import { writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const FONTS_DIR = path.resolve(__dirname, '../public/fonts')
const CSS_OUT   = path.resolve(__dirname, '../src/styles/fonts.css')

// Google Fonts API URL — request woff2 with a modern UA header
const API_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,400&family=Jost:wght@200;300;400;500;600&display=swap'

async function fetchText(url, headers = {}) {
  const res = await fetch(url, { headers })
  if (!res.ok) throw new Error(`HTTP ${res.status} — ${url}`)
  return res.text()
}

async function fetchBinary(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status} — ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

async function run() {
  await mkdir(FONTS_DIR, { recursive: true })

  // Request the CSS with a modern Chrome UA so Google sends woff2
  const css = await fetchText(API_URL, {
    'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
  })

  console.log('\nDownloaded font CSS from Google Fonts\n')

  // Extract all woff2 src urls
  const urlRe = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g
  const urls = [...css.matchAll(urlRe)].map((m) => m[1])
  console.log(`Found ${urls.length} woff2 file(s)\n`)

  // Download each font file
  const map = {}
  for (const url of urls) {
    const hash = url.split('/').pop() // e.g. 92zatBhPN….woff2
    const filename = hash
    const dest = path.join(FONTS_DIR, filename)
    const buf = await fetchBinary(url)
    await writeFile(dest, buf)
    map[url] = `/fonts/${filename}`
    console.log(`  ✓ ${filename}  (${Math.round(buf.length / 1024)} KiB)`)
  }

  // Rewrite CSS to use local paths
  let localCss = css.replace(
    /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g,
    (_, u) => `url('${map[u]}')`
  )

  // Ensure font-display: optional (prevents invisible text + layout shift)
  localCss = localCss.replace(/font-display: swap;/g, 'font-display: optional;')

  // Add header comment
  localCss = `/* Self-hosted fonts — generated by scripts/download-fonts.mjs */\n/* font-display:optional prevents FOUT and layout shifts */\n\n${localCss}`

  await writeFile(CSS_OUT, localCss, 'utf-8')
  console.log(`\n  ✓ Wrote ${CSS_OUT}\n`)
  console.log('Done! Import fonts.css in global.css and remove the Google Fonts <link> from index.html\n')
}

run().catch((err) => { console.error(err); process.exit(1) })
